🚧Fix sync issue with pr template (#120)
* Start work for issue #119

* chore: improve logging issue

* fix: fix issue with handling null func param

* fix: fix issue with pulling the template from the wrong branch

* chore: improve logging of pr sync template notice log message

* refactor: swap logic with pr sync template file check

* fix: fix issue with func not getting required param

* feat: add utils func to trim all values of a string array

* feat: add funcs to var service that checks if variables exist

* feat: add utils func to auto-number string items

* feat: create utils funcs to print multiple notices or errors

* refactor: move 'sync issue to pr' script to a runner

* config: add gitignore for accidental vscode csharp profile usage

* refactor: improve arg and required org/repo var validation for send release tweet runner

* refactor: improve arg and required org/repo var validation for prepare release runner

* pr-changes: update func code docs

* ci: update all reusable workflow ref versions from v9.1.0 to v9.1.1

* refactor: improve how the sync issue to pr and sync status check works

BREAKING-CHANGE: This removes the sync command argument from the script

* refactor: improve status check runner

* refactor: improve prepare release runner

* refactor: improve send release tweet runner

* refactor: improve transpile readme runner

* feat: add new enums and remove unused type

* cleanup: remove unused utils func

* refactor: adjust code to meet coding standards

* ide: exclude playground from deno linting

* ide: improve launch configs

* ide: improve code snippet scope for yaml files

* misc: rename template file

* ci: improve workflow pwsh comments

* refactor: adjust equal operators to use 3 instead of 2 tokens

* ci: update all reusable workflow ref version from v9.1.1 to v10.0.0

diff --git a/.github/workflows/add-issue-to-project.yml b/.github/workflows/add-issue-to-project.yml
--- a/.github/workflows/add-issue-to-project.yml
+++ b/.github/workflows/add-issue-to-project.yml
@@ -36,6 +36,28 @@ jobs:
     name: Add Issue ${{ github.event.issue.number }} To Project
     runs-on: ubuntu-latest
     steps:
+      - name: Print Environment Variables
+        run: Get-ChildItem -Path Env:* | Sort-Object Name
+
+      - name: Validate Workflow Inputs
+        run: |
+          if ("${{ inputs.org-name }}" -eq "") {
+            Write-Host ":error::The 'org-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
+          if ("${{ inputs.org-project-name }}" -eq "") {
+            Write-Host ":error::The 'org-project-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
+          if ("${{ inputs.project-name }}" -eq "") {
+            Write-Host ":error::The 'project-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
       - name: Add To Project
         run: |
           # Get the raw json data using the GH CLI
diff --git a/.github/workflows/build-csharp-project.yml b/.github/workflows/build-csharp-project.yml
--- a/.github/workflows/build-csharp-project.yml
+++ b/.github/workflows/build-csharp-project.yml
@@ -34,9 +34,43 @@ on:
 
 
 jobs:
+  print_validate_workflow:
+    name: Print & Validate Build DotNet Proj Workflow
+    runs-on: ubuntu-latest
+    steps:
+      - name: Print Environment Variables
+        run: Get-ChildItem -Path Env:* | Sort-Object Name
+
+      - name: Validate Workflow Inputs
+        run: |
+          $sdkVersion = "${{ inputs.net-sdk-version }}".Trim().ToLower();
+          $sdkVersion = $sdkVersion.StartsWith("v") ? $sdkVersion.Substring(1) : $sdkVersion;
+
+          if ("${{ inputs.project-name }}".Trim().ToLower() -eq "") {
+            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
+          if ("${{ inputs.build-config }}".Trim().ToLower() -eq "") {
+            Write-Host "::error::The 'build-config' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
+          # Verify that the dotnet sdk version has valid syntax
+          if ($sdkVersion -match "[0-9]+\.[0-9]+\.[0-9]+") {
+            Write-Host "::notice::The 'net-sdk-version' workflow input is valid.";
+          } else {
+            Write-Host "::error::The 'net-sdk-version' workflow input is invalid.  Expected version format: '#.#.#'";
+            exit 1;
+          }
+
+
   resolve_proj_file_path:
     name: Resolving ${{ inputs.project-name }} Project File Path
-    uses: KinsonDigital/Infrastructure/.github/workflows/resolve-csharp-proj-file.yml@v9.1.0
+    needs: print_validate_workflow
+    uses: KinsonDigital/Infrastructure/.github/workflows/resolve-csharp-proj-file.yml@v10.0.0
     with:
       project-name: ${{ inputs.project-name }}
       base-path: ${{ inputs.base-path }}
diff --git a/.github/workflows/nuget-package-does-not-exist.yml b/.github/workflows/nuget-package-does-not-exist.yml
--- a/.github/workflows/nuget-package-does-not-exist.yml
+++ b/.github/workflows/nuget-package-does-not-exist.yml
@@ -18,25 +18,39 @@ on:
         required: true
         description: The version of the package to check.
         type: string
-      cicd-scripts-version:
-        required: true
-        description: The version of the CICD scripts to use.
-        type: string
 
 
 jobs:
-  build_script_url:
-    name: Build Script URL
-    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.1.0
-    with:
-      project-name: ${{ inputs.project-name }}
-      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}
+  print_validate_workflow:
+    name: Print & Validate NuGet Check Workflow
+    runs-on: ubuntu-latest
+    steps:
+      - name: Print Environment Variables
+        run: Get-ChildItem -Path Env:* | Sort-Object Name
+
+      - name: Validate Workflow Inputs
+        run: |
+          if ("${{ inputs.project-name }}".Trim().ToLower() -eq "") {
+            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
+            exit 1;
+          }
+        
+        
+          $version = "${{ inputs.version }}".Trim().ToLower();
+          $version = $version.StartsWith("v") ? $version.SubString(1) : "$version";
+
+          if ($version -match "[0-9]+\.[0-9]+\.[0-9]+(|-preview\.[0-9]+)") {
+            Write-Host "::notice::The 'version' workflow input is valid.";
+          } else {
+            Write-Host "::error::The 'version' workflow input is invalid.  Expected version format: 'v#.#.#' or 'v#.#.#-preview.#'";
+            exit 1;
+          }
 
 
   nuget_pkg_does_not_exist:
     name: Validate NuGet Package Does Not Exist
+    needs: print_validate_workflow
     runs-on: ubuntu-latest
-    needs: build_script_url
     steps:
       - name: Set Up Deno
         uses: denoland/setup-deno@v1
@@ -45,10 +59,16 @@ jobs:
 
       - name: Package Does Not Exist
         run: |
-          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/nuget-pkg-does-not-exist.ts";
+          # Construct the URL to the organizations CICD scripts
+          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
+          $scriptUrl = $scriptUrl.Replace("\", "/").Replace("//", "/");
+          $scriptUrl = $scriptUrl.EndsWith("/") ? $scriptUrl.Substring(0, $scriptUrl.Length - 1) : $scriptUrl;
+          $scriptUrl = "$scriptUrl/nuget-pkg-does-not-exist.ts";
+
+          Write-Host "::notice::NuGet Package Check Script URL: $scriptUrl";
 
           <# Deno Args:
-            1. PackageName
+            1. Package name
             2. Version
           #>
           deno run `
diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -1,4 +1,4 @@
-name: ✨Prepare Release
+name: 🚁Prepare Release
 
 
 defaults:
@@ -28,77 +28,80 @@ on:
 
 
 jobs:
-  validate_inputs:
-    name: Validate Inputs
+  print_validate_workflow:
+    name: Print & Validate Prepare Release Workflow
     runs-on: ubuntu-latest
     steps:
-      - name: Validating Inputs
-        run: |
-          $projectName = "${{ inputs.project-name }}";
-          $releaseType = "${{ inputs.release-type }}".ToLower();
-          $releaseVersion = "${{ inputs.release-version }}";
+      - name: Print Environment Variables
+        run: Get-ChildItem -Path Env:* | Sort-Object Name
 
-          if ($projectName -eq "") {
-            Write-Host "::error::The project name input cannot be empty.";
+      - name: Validate Workflow Inputs
+        run: |
+          $releaseType = "${{ inputs.release-type }}".Trim().ToLower();
+
+          if ("${{ inputs.project-name }}".Trim().ToLower() -eq "") {
+            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
             exit 1;
           }
 
 
           if ($releaseType -eq "") {
-            Write-Host "::error::The release type input cannot be empty.";
+            Write-Host "::error::The 'release-type' workflow input cannot be empty.";
             exit 1;
           }
 
 
           if ($releaseType -ne 'preview' -and $releaseType -ne 'roduction') {
-            Write-Host "::error::The release type input must be either 'Preview' or 'Production'.";
+            Write-Host "::error::The 'release-type' workflow input is invalid.  Expecting value of 'Preview' or 'Production'.";
             exit 1;
           }
 
 
-          if ($releaseVersion -eq "") {
-            Write-Host "::error::The release version input cannot be empty.";
-            exit 1;
-          }
+          $releaseVersion = "${{ inputs.release-version }}".Trim().ToLower();
+          $releaseVersion = $releaseVersion.StartsWith("v") ? $releaseVersion : "v$releaseVersion";
 
-
-          $prodVersionRegex = "v[0-9]+\.[0-9]+\.[0-9]+";
-          $prevVersionRegex = "v[0-9]+\.[0-9]+\.[0-9]+-preview\.[0-9]+";
-          
-          # Verify that the version has valid syntax
-          if (($version -match $prodVersionRegex) -or ($version -match $prevVersionRegex)) {
-            Write-Host "::notice::The version is valid.";
+          if ($releaseType -eq "production") {
+            if ($releaseVersion -notmatch "v[0-9]+\.[0-9]+\.[0-9]+") {
+              Write-Host "::error::The production release version input is invalid. Expected version format: 'v#.#.#'";
+              exit 1;
+            }
           } else {
-            $versionSyntax = $releaseType == "production" ? "v#.#.#" : "v#.#.#-preview.#";
-            Write-Host "::error::The version is not valid.\nThe version format is: '$versionSyntax";
-            exit 1;
+            if ($releaseVersion -notmatch "v[0-9]+\.[0-9]+\.[0-9]+-preview\.[0-9]+") {
+              Write-Host "::error::The preview release version input is invalid. Expected version format: 'v#.#.#-preview.#'";
+              exit 1;
+            }
           }
-
-
-  build_script_url:
-    name: Build Script URL
-    needs: validate_inputs
-    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.1.0
-    with:
-      project-name: "${{ inputs.project-name }}"
-      cicd-scripts-version: "${{ vars.CICD_SCRIPTS_VERSION }}"
 
 
   prepare_release:
     name: Prepare ${{ inputs.release-type }} Release
-    needs: build_script_url
+    needs: print_validate_workflow
     runs-on: ubuntu-latest
     steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
+
+      - name: Set Up Deno
+        uses: denoland/setup-deno@v1
+        with:
+          deno-version: v1.x
+
       - name: Generate Release Notes
         run: |
-          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/prepare-release.ts";
+          # Construct the URL to the organizations CICD scripts
+          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
+          $scriptUrl = $scriptUrl.Replace("\", "/").Replace("//", "/");
+          $scriptUrl = $scriptUrl.EndsWith("/") ? $scriptUrl.Substring(0, $scriptUrl.Length - 1) : $scriptUrl;
+          $scriptUrl = "$scriptUrl/prepare-release.ts";
+
+          Write-Host "::notice::NuGet Package Check Script URL: $scriptUrl";
 
           <# Deno Args:
-            1. Organization Name
-            2. Project Name
-            3. Release Type - 'production' or 'preview'
-            4. Release Version
-            5. CICD PAT
+            1. Organization name
+            2. Project name
+            3. Release type - 'production' or 'preview'
+            4. Release version
+            5. PAT
           #>
           deno run `
             --allow-read --allow-write --allow-net `
@@ -107,5 +110,4 @@ jobs:
             "${{ inputs.project-name }}" `
             "${{ inputs.release-type }}" `
             "${{ inputs.release-version }}" `
-            "${{ github.workspace }}" `
             "${{ secrets.cicd-pat }}";
diff --git a/.github/workflows/run-csharp-tests.yml b/.github/workflows/run-csharp-tests.yml
--- a/.github/workflows/run-csharp-tests.yml
+++ b/.github/workflows/run-csharp-tests.yml
@@ -33,9 +33,46 @@ on:
 
 
 jobs:
+  print_validate_workflow:
+    name: Print & Validate Run DotNet Tests Workflow
+    runs-on: ubuntu-latest
+    steps:
+      - name: Print Environment Variables
+        run: Get-ChildItem -Path Env:* | Sort-Object Name
+
+      - name: Validate Workflow Inputs
+        run: |
+          # Verify that the project name workflow input is not empty
+          if ("${{ inputs.project-name }}".Trim().ToLower() -eq "") {
+            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
+          $buildConfig = "${{ inputs.build-config }}".Trim().ToLower();
+
+          # Verify that the build config is only 'Debug' or 'Release'
+          if ($buildConfig -ne "Debug" -and $buildConfig -ne "Release") {
+            Write-Host "::error::The 'build-config' workflow input is invalid.  Expecting a value of 'Debug' or 'Release'.";
+            exit 1;
+          }
+
+
+          $sdkVersion = "${{ inputs.net-sdk-version }}".Trim().ToLower();
+          
+          # Verify that the dotnet sdk version has valid syntax
+          if ($sdkVersion -match "[0-9]+\.[0-9]+\.[0-9]+") {
+            Write-Host "::notice::The 'net-sdk-version' workflow input is valid.";
+          } else {
+            Write-Host "::error::The 'net-sdk'version' workflow input is invalid.  Expected version format: '#.#.#'";
+            exit 1;
+          }
+
+
   resolve_proj_file_path:
     name: Resolving ${{ inputs.project-name }} Project File Path
-    uses: KinsonDigital/Infrastructure/.github/workflows/resolve-csharp-proj-file.yml@v9.1.0
+    needs: print_validate_workflow
+    uses: KinsonDigital/Infrastructure/.github/workflows/resolve-csharp-proj-file.yml@v10.0.0
     with:
       project-name: ${{ inputs.project-name }}
       base-path: ${{ inputs.base-path }}
@@ -43,7 +80,7 @@ jobs:
 
   run_unit_tests:
     name: Run Unit Tests
-    needs: resolve_proj_file_path
+    needs: [print_validate_workflow, resolve_proj_file_path]
     runs-on: ${{ inputs.runs-on }}
     steps:
       - uses: actions/checkout@v3
diff --git a/.github/workflows/validate-github-release.yml b/.github/workflows/validate-github-release.yml
--- a/.github/workflows/validate-github-release.yml
+++ b/.github/workflows/validate-github-release.yml
@@ -17,10 +17,6 @@ on:
         required: true
         description: The version of the release to validate.
         type: string
-      cicd-scripts-version:
-        required: true
-        description: The version of the CICD scripts to use.
-        type: string
     secrets:
       cicd-pat:
         required: true
@@ -28,18 +24,38 @@ on:
       
 
 jobs:
-  build_script_url:
-    name: Build Script URL
-    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.1.0
-    with:
-      project-name: ${{ inputs.project-name }}
-      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}
+  print_validate_workflow:
+    name: Print & Validate GitHub Release Workflow
+    runs-on: ubuntu-latest
+    steps:
+      - name: Print Environment Variables
+        run: Get-ChildItem -Path Env:* | Sort-Object Name
+
+      - name: Validate Workflow Inputs
+        run: |
+          # Verify that the project name workflow input is not empty
+          if ("${{ inputs.project-name }}".Trim().ToLower() -eq "") {
+            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
+          $version = "${{ inputs.version }}".Trim().ToLower();
+          $version = $version.StartsWith("v") ? $version : "v$version";
+
+          # Verify that the version workflow input is valid
+          if ($version -match "v[0-9]+\.[0-9]+\.[0-9]+(|-preview\.[0-9]+)") {
+            Write-Host "::notice::The 'version' workflow input is valid.";
+          } else {
+            Write-Host "::error::The 'version' workflow input is invalid.  Expected version format: 'v#.#.#(-preview.#)'";
+            exit 1;
+          }
 
 
   validate_github_release:
     name: Validate GitHub Release
+    needs: print_validate_workflow
     runs-on: ubuntu-latest
-    needs: build_script_url
     steps:
       - name: Set Up Deno
         uses: denoland/setup-deno@v1
@@ -48,12 +64,18 @@ jobs:
 
       - name: GitHub Release Does Not Exist 
         run: |
-          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/github-release-does-not-exist.ts";
+          # Construct the URL to the organizations CICD scripts
+          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
+          $scriptUrl = $scriptUrl.Replace("\", "/").Replace("//", "/");
+          $scriptUrl = $scriptUrl.EndsWith("/") ? $scriptUrl.Substring(0, $scriptUrl.Length - 1) : $scriptUrl;
+          $scriptUrl = "$scriptUrl/github-release-does-not-exist.ts";
+
+          Write-Host "::notice::Validate GitHub Release Version Script URL: $scriptUrl";
 
           <# Deno Args:
-            1. RepoName
-            2. TagName - This is the version
-            3. GitHubToken
+            1. Repo name
+            2. TagName - This is prev or prod version
+            3. PAT
           #>
           deno run `
             --allow-net `
@@ -61,4 +83,3 @@ jobs:
             "${{ inputs.project-name }}" `
             "${{ inputs.version }}" `
             "${{ secrets.cicd-pat }}";
-
diff --git a/.github/workflows/validate-milestone-status.yml b/.github/workflows/validate-milestone-status.yml
--- a/.github/workflows/validate-milestone-status.yml
+++ b/.github/workflows/validate-milestone-status.yml
@@ -17,10 +17,6 @@ on:
         required: true
         description: The version of the milestone to validate.
         type: string
-      cicd-scripts-version:
-        required: true
-        description: The version of the CICD scripts to use.
-        type: string
     secrets:
       cicd-pat:
         required: true
@@ -28,31 +24,63 @@ on:
       
 
 jobs:
-  build_script_url:
-    name: Build Script URL
-    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.1.0
-    with:
-      project-name: ${{ inputs.project-name }}
-      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}
+  print_validate_workflow:
+    name: Print & Validate Milestone Status Workflow
+    runs-on: ubuntu-latest
+    steps:
+      - name: Print Environment Variables
+        run: Get-ChildItem -Path Env:* | Sort-Object Name
+
+      - name: Validate Workflow Inputs
+        run: |
+          # Verify that the project name workflow input is not empty
+          if ("${{ inputs.project-name }}".Trim().ToLower() -eq "") {
+            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
+          $version = "${{ inputs.version }}".Trim().ToLower();
+          $version = $version.StartsWith("v") ? $version : "v$version";
+
+          # Verify that the version workflow input is valid
+          if ($version -match "v[0-9]+\.[0-9]+\.[0-9]+(|-preview\.[0-9]+)") {
+            Write-Host "::notice::The 'version' workflow input is valid.";
+          } else {
+            Write-Host "::error::The 'version' workflow input is invalid.  Expected version format: 'v#.#.#(-preview.#)'";
+            exit 1;
+          }
+
 
   validate_milestone_status:
     name: Validate Milestone Status
+    needs: print_validate_workflow
     runs-on: ubuntu-latest
-    needs: build_script_url
     steps:
       - name: Set Up Deno
         uses: denoland/setup-deno@v1
         with:
           deno-version: v1.x
 
+      - name: Create Script URL
+        id: script-url
+        run: |
+          # Construct the URL to the organizations CICD scripts
+          $url = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
+          $url = $url.Replace("\", "/").Replace("//", "/");
+          $url = $url.EndsWith("/") ? $url.Substring(0, $url.Length - 1) : $url;
+          
+          Write-Host "::notice::DotNet Lib Release Script URL: $url";
+          "url=$url" >> "$env:GITHUB_OUTPUT";
+
       - name: Milestone Exists
         run: |
-          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/milestone-exists.ts";
+          $scriptUrl = "${{ steps.script-url.outputs.url }}/milestone-exists.ts";
 
           <# Deno Args:
-            1. RepoName
-            2. MilestoneTitle - This is the version
-            3. GitHubToken
+            1. Project name
+            2. Milestone title - This is a prev or prod version
+            3. PAT
           #>
           deno run `
             --allow-net `
@@ -63,12 +91,12 @@ jobs:
 
       - name: Validate Milestone
         run: |
-          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/milestone-items-all-closed.ts";
+          $scriptUrl = "${{ steps.script-url.outputs.url }}/milestone-items-all-closed.ts";
         
           <# Deno Args:
-            1. RepoName
-            2. MilestoneTitle - This is the version
-            3. GitHubToken
+            1. Repo name
+            2. MilestoneTitle - This is a prev or prod version
+            3. PAT
           #>
           deno run `
             --allow-read --allow-net `
diff --git a/.github/workflows/validate-tag.yml b/.github/workflows/validate-tag.yml
--- a/.github/workflows/validate-tag.yml
+++ b/.github/workflows/validate-tag.yml
@@ -21,10 +21,6 @@ on:
         required: true
         description: The name of the tag to validate.
         type: string
-      cicd-scripts-version:
-        required: true
-        description: The version of the CICD scripts to use.
-        type: string
     secrets:
       cicd-pat:
         required: true
@@ -33,63 +29,45 @@ on:
         
 jobs:
   validate_workflow_inputs:
-    name: Validate Workflow Inputs
+    name: Print & Validate Tag Workflow
     runs-on: ubuntu-latest
     steps:
       - name: Validate Inputs
         run: |
           # Verify that the project name workflow input is not empty
-          if ("${{ inputs.project-name }}" -eq "") {
+          if ("${{ inputs.project-name }}".Trim().ToLower() -eq "") {
             Write-Host "::error::The 'project-name' workflow input cannot be empty.";
             exit 1;
           }
 
 
-          $releaseType = "${{ inputs.release-type }}";
+          $releaseType = "${{ inputs.release-type }}".Trim().ToLower();
 
           # Verify that the release type is only 'Preview' or 'Production'
           if ($releaseType -ne "Preview" -and $releaseType -ne "Production") {
-            Write-Host "::error::The release type '$releaseType' is invalid.  Valid values are 'Preview' or 'Production'.";
+            Write-Host "::error::The 'release-type' workflow input is invalid.  Expecting value of 'Preview' or 'Production'.";
             exit 1;
           }
 
 
-          $tagName = "${{ inputs.tag-name }}";
-          $tagNameRegex = "v[0-9]+\.[0-9]+\.[0-9]+";
-          
-          # Verify that the cicd script version has valid syntax
-          if ($tagName -match $tagNameRegex) {
-            Write-Host "::notice::The tag name is valid.";
+          $tagName = "${{ inputs.tag-name }}".Trim().ToLower();
+
+          if ($releaseType -eq "production") {
+            if ($tagName -notmatch "v[0-9]+\.[0-9]+\.[0-9]+") {
+              Write-Host "::error::The 'tag-name' workflow input is invalid. Expected version format: 'v#.#.#'";
+              exit 1;
+            }
           } else {
-            Write-Host "::error::The tag name is not valid.\nThe version format is: 'v#.#.#'";
-            exit 1;
+            if ($tagName -notmatch "v[0-9]+\.[0-9]+\.[0-9]+-preview\.[0-9]+") {
+              Write-Host "::error::The 'tag-name' workflow input is invalid. Expected version format: 'v#.#.#-preview.#'";
+              exit 1;
+            }
           }
-
-
-          $cicdScriptVersion = "${{ inputs.cicd-scripts-version }}";
-          $cicdScriptVersionRegex = "v[0-9]+\.[0-9]+\.[0-9]+";
-          
-          # Verify that the cicd script version has valid syntax
-          if ($cicdScriptVersion -match $cicdScriptVersionRegex) {
-            Write-Host "::notice::The cicd script version is valid.";
-          } else {
-            Write-Host "::error::The cicd script version is not valid.\nThe version format is: 'v#.#.#'";
-            exit 1;
-          }
-
-
-  build_script_url:
-    name: Build Script URL
-    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.1.0
-    with:
-      project-name: ${{ inputs.project-name }}
-      cicd-scripts-version: ${{ inputs.cicd-scripts-version }}
 
 
   validate_tag:
     name: Validate Tag
     runs-on: ubuntu-latest
-    needs: build_script_url
     steps:
       - name: Set Up Deno
         uses: denoland/setup-deno@v1
@@ -98,13 +76,19 @@ jobs:
 
       - name: Validate Tag
         run: |
-          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/validate-tag.ts";
+          # Construct the URL to the organizations CICD scripts
+          $scriptUrl = "${{ vars.SCRIPT_BASE_URL }}/${{ vars.CICD_SCRIPTS_VERSION }}/${{ vars.SCRIPT_RELATIVE_DIR_PATH }}";
+          $scriptUrl = $scriptUrl.Replace("\", "/").Replace("//", "/");
+          $scriptUrl = $scriptUrl.EndsWith("/") ? $scriptUrl.Substring(0, $scriptUrl.Length - 1) : $scriptUrl;
+          $scriptUrl = "$scriptUrl/validate-tag.ts";
+
+          Write-Host "::notice::Validate Tag Script URL: $scriptUrl";
         
           <# Deno Args:
-            1. Repo Name
-            2. Tag Type
-            3. Release Type - Either 'Preview' or 'Production'
-            3. Tag Name - This is the version
+            1. Repo name
+            2. Tag type
+            3. Release type - Either 'Preview' or 'Production'
+            3. Tag name - This is the version
             4. PAT
           #>
           deno run `
