🚧Change how release note validation works (#104)
* Start work for issue #103

* ci: refactor release note validation job

* ci: refactor all echo commands to use the Write-Host commandlet

* ci: improve logging in all workflows

* ci: make various improvements such as logging, input descriptions, job and step names, and style

* ci: add runs-on workflow input to build and test workflows

* ci: set build and test workflows to use resolve proj file reusable workflow

* ci: update all reusable workflow refs to use latest infrastructure version

* ci: sanitize paths in release note validation job

diff --git a/.github/workflows/dotnet-action-release.yml b/.github/workflows/dotnet-action-release.yml
--- a/.github/workflows/dotnet-action-release.yml
+++ b/.github/workflows/dotnet-action-release.yml
@@ -12,7 +12,7 @@ on:
     inputs:
       project-name:
         required: true
-        description: The name of the C# project to validate.
+        description: "The name of the C# project to validate."
         type: string
       release-type:
         required: true
@@ -43,6 +43,11 @@ on:
         required: true
         description: The version of the CICD scripts to use.
         type: string
+      runs-on:
+        required: false
+        description: The type of machine to run the job on.
+        type: string
+        default: ubuntu-latest
       pr-include-notes-label:
         required: false
         description: The label on a pull request that forces its inclusion in the release notes.
@@ -64,7 +69,7 @@ jobs:
         run: |
           # Verify that the project name workflow input is not empty
           if ("${{ inputs.project-name }}" -eq "") {
-            echo "The 'project-name' workflow input cannot be empty.";
+            Write-Host "::error::The 'project-name' workflow input cannot be empty.";
             exit 1;
           }
 
@@ -73,14 +78,14 @@ jobs:
 
           # Verify that the release type is only 'Preview' or 'Production'
           if ($releaseType -ne "Preview" -and $releaseType -ne "Production") {
-            echo "The release type '$releaseType' is invalid.  Valid values are 'Preview' or 'Production'.";
+            Write-Host "::error::The release type '$releaseType' is invalid.  Valid values are 'Preview' or 'Production'.";
             exit 1;
           }
 
 
           # Verify that the run branch workflow input is not empty
           if ("${{ inputs.run-branch }}" -eq "") {
-            echo "The 'run-branch' workflow input cannot be empty.";
+            Write-Host "::error::The 'run-branch' workflow input cannot be empty.";
             exit 1;
           }
 
@@ -90,9 +95,9 @@ jobs:
           
           # Verify that the dotnet sdk version has valid syntax
           if ($sdkVersion -match $sdkVersionRegex) {
-            echo "The dotnet SDK version is valid.";
+            Write-Host "::notice::The dotnet SDK version is valid.";
           } else {
-            echo "::error::The dotnet SDK version is not valid.\nThe version format is: '#.#.#'";
+            Write-Host "::error::The dotnet SDK version is not valid.\nThe version format is: '#.#.#'";
             exit 1;
           }
 
@@ -103,14 +108,14 @@ jobs:
           
           # Verify that the relative release notes dir path does not start or end with a with a forward or back slash
           if ($dirPath.StartsWith($backSlash) -or $dirPath.StartsWith($forwardSlash) -or $dirPath.EndsWith($backSlash) -or $dirPath.EndsWith($forwardSlash)) {
-            echo "The 'relative-release-notes-dir-path' cannot start or end with a forward or back slash.";
+            Write-Host "::error::The 'relative-release-notes-dir-path' cannot start or end with a forward or back slash.";
             exit 1;
           }
 
 
           # Verify that the release notes file name prefix workflow input is not empty
           if ("${{ inputs.release-notes-file-name-prefix }}" -eq "") {
-            echo "The 'release-notes-file-name-prefix' workflow input cannot be empty.";
+            Write-Host "::error::The 'release-notes-file-name-prefix' workflow input cannot be empty.";
             exit 1;
           }
 
@@ -119,7 +124,7 @@ jobs:
 
           # Verify that the build config is only 'Debug' or 'Release'
           if ($buildConfig -ne "Debug" -and $buildConfig -ne "Release") {
-            echo "The build configuration '$buildConfig' is invalid.  The build configuration can only be 'Debug' or 'Release'.";
+            Write-Host "::error::The build configuration '$buildConfig' is invalid.  The build configuration can only be 'Debug' or 'Release'.";
             exit 1;
           }
 
@@ -129,15 +134,15 @@ jobs:
           
           # Verify that the cicd script version has valid syntax
           if ($cicdScriptVersion -match $cicdScriptVersionRegex) {
-            echo "The cicd script version is valid.";
+            Write-Host "::notice::The cicd script version is valid.";
           } else {
-            echo "::error::The cicd script version is not valid.\nThe version format is: 'v#.#.#'";
+            Write-Host "::error::The cicd script version is not valid.\nThe version format is: 'v#.#.#'";
             exit 1;
           }
 
 
   validate_branch:
-    name: Validate Branch
+    name: Validate Branch (${{ inputs.run-branch }})
     runs-on: ubuntu-latest
     needs: validate_workflow_inputs
     steps:
@@ -146,7 +151,7 @@ jobs:
           $branch = "${{ github.ref_name }}"
 
           if ($branch -ne "${{ inputs.run-branch }}") {
-            echo "The branch '$branch' is invalid. This release can only run on '${{ inputs.run-branch }}' branches."
+            Write-Host "::error::The branch '$branch' is invalid. This release can only run on '${{ inputs.run-branch }}' branches."
             exit 1;
           }
 
@@ -154,7 +159,7 @@ jobs:
   validate_version:
     name: Validate Version
     needs: validate_branch
-    uses: KinsonDigital/Infrastructure/.github/workflows/validate-csharp-version.yml@v8.0.0
+    uses: KinsonDigital/Infrastructure/.github/workflows/validate-csharp-version.yml@v8.1.0
     with:
       project-name: "${{ inputs.project-name }}"
       release-type: "${{ inputs.release-type }}"
@@ -166,7 +171,7 @@ jobs:
   validate_tag:
     name: Validate Tag
     needs: validate_version
-    uses: KinsonDigital/Infrastructure/.github/workflows/validate-tag.yml@v8.0.0
+    uses: KinsonDigital/Infrastructure/.github/workflows/validate-tag.yml@v8.1.0
     with:
       project-name: "${{ inputs.project-name }}"
       release-type: "${{ inputs.release-type }}"
@@ -176,24 +181,34 @@ jobs:
       cicd-pat: "${{ secrets.cicd-pat }}"
 
 
-  validate_release_notes:
-    name: Validate Release Notes
+  validate_release_notes_exist:
+    name: Validate Release Notes Exist
     needs: validate_version
-    uses: KinsonDigital/Infrastructure/.github/workflows/validate-release-notes.yml@v8.0.0
-    with:
-      org-name: "${{ vars.ORGANIZATION_NAME }}"
-      project-name: "${{ inputs.project-name }}"
-      release-type: "${{ inputs.release-type }}"
-      version: "${{ needs.validate_version.outputs.version }}"
-      cicd-scripts-version: "${{ inputs.cicd-scripts-version }}"
-    secrets:
-      cicd-pat: "${{ secrets.cicd-pat }}"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Release Notes Exist
+        run: |
+          $relativeDirPath = "${{ inputs.relative-release-notes-dir-path }}";
+        
+          # Remove all leading forwaard slashes until non are left
+          $relativeDirPath = $relativeDirPath.Replace("\", "/");
+          $relativeDirPath = $relativeDirPath.TrimStart("/").TrimEnd("/");
+
+          $dirPath = "${{ github.workspace }}/$relativeDirPath";
+          $version = "${{ needs.validate_version.outputs.version }}";
+          $fileName = "${{ inputs.release-notes-file-name-prefix }}$version.md";
+          $filePath = "$dirPath/$fileName";
+
+          if (-not(Test-Path $filePath)) {
+            Write-Host "::error::The release notes file '$filePath' does not exist.";
+            exit 1;
+          }
 
 
   validate_github_release:
     name: GitHub Release Does Not Exist
     needs: [validate_version]
-    uses: KinsonDigital/Infrastructure/.github/workflows/validate-github-release.yml@v8.0.0
+    uses: KinsonDigital/Infrastructure/.github/workflows/validate-github-release.yml@v8.1.0
     with:
       project-name: "${{ inputs.project-name }}"
       version: "${{ needs.validate_version.outputs.version }}"
@@ -203,21 +218,23 @@ jobs:
 
 
   build_project:
-    name: Build Main Project
-    needs: [validate_tag, validate_release_notes, validate_github_release]
-    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v8.0.0
+    name: Build Main Project (${{ inputs.project-name }})
+    needs: [validate_tag, validate_release_notes_exist, validate_github_release]
+    uses: KinsonDigital/Infrastructure/.github/workflows/build-csharp-project.yml@v8.1.0
     with:
       project-name: "${{ inputs.project-name }}"
+      runs-on: "${{ inputs.runs-on }}"
       build-config: "${{ inputs.build-config }}"
       net-sdk-version: "${{ inputs.net-sdk-version }}"
 
 
   run_tests:
     name: Run Tests
-    needs: [validate_tag, validate_release_notes, validate_github_release]
-    uses: KinsonDigital/Infrastructure/.github/workflows/run-csharp-tests.yml@v8.0.0
+    needs: [validate_tag, validate_release_notes_exist, validate_github_release]
+    uses: KinsonDigital/Infrastructure/.github/workflows/run-csharp-tests.yml@v8.1.0
     with:
       project-name: "${{ inputs.project-name }}Tests"
+      runs-on: "${{ inputs.runs-on }}"
       build-config: "${{ inputs.build-config }}"
       net-sdk-version: "${{ inputs.net-sdk-version }}"
         
diff --git a/.github/workflows/resolve-csharp-proj-file.yml b/.github/workflows/resolve-csharp-proj-file.yml
--- a/.github/workflows/resolve-csharp-proj-file.yml
+++ b/.github/workflows/resolve-csharp-proj-file.yml
@@ -11,15 +11,15 @@ on:
     inputs:
       project-name:
         required: true
-        description: The name of the C# project to validate
+        description: "The name of the C# project to validate."
         type: string
       base-path:
         required: false
-        description: The base directory path to start the search from
+        description: The base directory path to start the search.
         type: string
     outputs:
       project-file-path:
-        description: The resolve csharp project file path
+        description: The resolve csharp project file path.
         value: ${{ jobs.resolve_proj_file_path.outputs.project-file-path }}
 
 
@@ -45,17 +45,17 @@ jobs:
 
         # If null, no project file was found
         if (!$result) {
-            echo "::error::Project file not found";
-            exit 1; # Fail Workflow
+          Write-Host "::error::Project file not found";
+          exit 1; # Fail Workflow
         } elseif ($resultType -ne "String") {
-            echo "::error::Found too many project files!!";
+          Write-Host "::error::Found too many project files!!";
 
-            foreach ($item in $result) {
-                echo "`t$item";
-            }
+          foreach ($item in $result) {
+              Write-Host "`t$item";
+          }
 
-            exit 1; # Fail Workflow
+          exit 1; # Fail Workflow
         } else {
-            echo "Resolved file path 👉🏼 $result";
-            "project-file-path=$result" >> $env:GITHUB_OUTPUT;
+          Write-Host "::notice::Project File Path Resolved To: $result";
+          "project-file-path=$result" >> $env:GITHUB_OUTPUT;
         }
