🚧Move reusable workflows (#117)
* Start work for issue #116

* fix: move workflows into correct folder

* fix: update paths to reusable workflows

* ci: update all reusable workflow reference versions

diff --git a/.github/workflows/validate-release-notes.yml b/.github/workflows/validate-release-notes.yml
--- a/.github/workflows/validate-release-notes.yml
+++ b/.github/workflows/validate-release-notes.yml
@@ -1,4 +1,4 @@
-name: Validate CSharp Version
+name: Validate Release Notes
 
 
 defaults:
@@ -9,6 +9,10 @@ defaults:
 on:
   workflow_call:
     inputs:
+      org-name:
+        required: true
+        description: The name of GitHub organization.
+        type: string
       project-name:
         required: true
         description: "The name of the C# project to validate."
@@ -17,20 +21,19 @@ on:
         required: true
         description: The type of release to validate.  Either 'Preview' or 'Production'.
         type: string
+      version:
+        required: true
+        description: The version of the release notes to validate.
+        type: string
       cicd-scripts-version:
         required: true
         description: The version of the CICD scripts to use.
         type: string
-    outputs:
-      version:
-        description: The version pulled from the csproj file.
-        value: ${{ jobs.validate_version.outputs.version }}
     secrets:
       cicd-pat:
         required: true
         description: The CICD personal access token.
-        
-
+      
 
 jobs:
   validate_workflow_inputs:
@@ -39,18 +42,38 @@ jobs:
     steps:
       - name: Validate Inputs
         run: |
+          # Verify that the organization name workflow input is not empty
+          if ("${{ inputs.org-name }}" -eq "") {
+            Write-Host "::error::The 'org-name' workflow input cannot be empty.";
+            exit 1;
+          }
+
+
           # Verify that the project name workflow input is not empty
           if ("${{ inputs.project-name }}" -eq "") {
             Write-Host "::error::The 'project-name' workflow input cannot be empty.";
             exit 1;
           }
 
-
+          
           $releaseType = "${{ inputs.release-type }}";
 
           # Verify that the release type is only 'Preview' or 'Production'
           if ($releaseType -ne "Preview" -and $releaseType -ne "Production") {
             Write-Host "::error::The release type '$releaseType' is invalid.  Valid values are 'Preview' or 'Production'.";
+            exit 1;
+          }
+
+
+          $version = "${{ inputs.cicd-scripts-version }}";
+          $prodVersionRegex = "v[0-9]+\.[0-9]+\.[0-9]+";
+          $prevVersionRegex = "v[0-9]+\.[0-9]+\.[0-9]+-preview\.[0-9]+";
+          
+          # Verify that the version has valid syntax
+          if (($version -match $prodVersionRegex) -or ($version -match $prevVersionRegex)) {
+            Write-Host "::notice::The version is valid.";
+          } else {
+            Write-Host "::error::The version is not valid.\nThe version format is: 'v#.#.#' or 'v#.#.#-preview.#'";
             exit 1;
           }
 
@@ -69,56 +92,41 @@ jobs:
 
   build_script_url:
     name: Build Script URL
-    uses: KinsonDigital/Infrastructure/.github/workflows/reusable/create-script-url.yml@v9.0.0
+    uses: KinsonDigital/Infrastructure/.github/workflows/create-script-url.yml@v9.0.1
     with:
       project-name: ${{ inputs.project-name }}
       cicd-scripts-version: ${{ inputs.cicd-scripts-version }}
 
 
-  validate_version:
-    name: Get And Validate Version
+  validate_release_notes:
+    name: Validate Release Notes
     runs-on: ubuntu-latest
     needs: build_script_url
-    outputs:
-      version: ${{ steps.validate-version.outputs.version }}
     steps:
-      - name: Get Version From Project File
-        id: get-version
-        uses: KinsonDigital/VersionMiner@v1.0.0-preview.5
-        with:
-          repo-owner: ${{ vars.ORGANIZATION_NAME }}
-          repo-name: ${{ inputs.project-name }}
-          repo-token: ${{ secrets.cicd-pat }}
-          branch-name: '${{ github.ref_name }}'
-          file-format: 'xml' # Not case sensitive
-          file-path: '${{ inputs.project-name }}/${{ inputs.project-name }}.csproj'
-          version-keys: Version
-        
       - name: Set Up Deno
         uses: denoland/setup-deno@v1
         with:
           deno-version: v1.x
-        
-      - name: Validate Version
-        id: validate-version
+
+      - name: Checkout Repo
+        uses: actions/checkout@v3
+
+      - name: Validate Release Notes
         run: |
-          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/validate-version.ts";
-
-          # Get the release version and make sure it starts with the letter 'v'
-          $releaseVersion = "${{ steps.get-version.outputs.version }}";
-
-          Write-Host "::notice::Release Version Before Mutation: $releaseVersion";
-          $releaseVersion = $releaseVersion.StartsWith("v") ? $releaseVersion : "v" + $releaseVersion;
-          Write-Host "::notice::Release Version After Mutation: $releaseVersion";
-
-          # Set the output of this step
-          "version=$releaseVersion" >> $env:GITHUB_OUTPUT;
-
+          $scriptUrl = "${{ needs.build_script_url.outputs.script-url }}/validate-release-notes.ts";
+        
           <# Deno Args:
-            1. Version
-            2. Version Type
+            1. GitHub Orgnization Name
+            2. GitHub Repo Name
+            3. Release Type - Either 'Preview' or 'Production'
+            4. Version
+            5. GitHub PAT Token
           #>
           deno run `
+            --allow-read --allow-net `
             "$scriptUrl" `
-            "$releaseVersion" `
-            "${{ inputs.release-type }}";
+            "${{ inputs.org-name }}" `
+            "${{ inputs.project-name }}" `
+            "${{ inputs.release-type }}" `
+            "${{ inputs.version }}" `
+            "${{ secrets.cicd-pat }}";
